openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /consulta-endereco:
    get:
      tags:
      - consulta-endereco-controller
      operationId: getEndereco
      parameters:
      - name: request
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/ConsultaEnderecoRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Endereco'
        "404":
          description: Cep não encontrado
        "400":
          description: Requisição Inválida
components:
  schemas:
    ConsultaEnderecoRequest:
      type: object
      properties:
        cep:
          type: string
    Endereco:
      type: object
      properties:
        cep:
          type: string
        rua:
          type: string
        complemento:
          type: string
        bairro:
          type: string
        cidade:
          type: string
        estado:
          type: string
          enum:
          - AC
          - AL
          - AP
          - AM
          - BA
          - CE
          - DF
          - ES
          - GO
          - MA
          - MT
          - MS
          - MG
          - PA
          - PB
          - PR
          - PE
          - PI
          - RJ
          - RN
          - RS
          - RO
          - RR
          - SC
          - SP
          - SE
          - TO
        frete:
          type: number
